### ISSUE TITLE
Is the sgrasp_file necessary for Model Based Grasping?

### ISSUE THREAD

**Issue by ZhengLeon** [IRVLUTD/SceneReplica#2]
Hi @07hokage ,
When I tried to run `python bench_model_based_grasping.py`, it shows that the [sgrasps.pk](https://github.com/IRVLUTD/SceneReplica/blob/main/src/bench_model_based_grasping.py#L435) is missed.
May I ask if this checkpoint be released later?

**Comment by 07hokage** [comment]
Hi @ZhengLeon , the sgraps.pk file contains possible successful grasps among all other grasps. The algorithm checks their feasibility first and then for the rest.  File has been uploaded to the repository [here](https://utdallas.app.box.com/file/1258866597024?s=ptv8ms4l1kl13kwvvx8w2nn8i7e38stq) .  The same has been updated in the documentation too. Thanks for pointing this out.  Let us know if this is working at your end

**Comment by ZhengLeon** [comment]
Hi @07hokage , thanks for your help.
After add the `sgrasps.pk`, I still met some error when I run the script `python bench_model_based_grasping.py`:
```
[ERROR] [1689305130.275655975]: Robot semantic description not found. Did you forget to define or remap '/robot_description_semantic'?
[ INFO] [1689305130.276275641]: Loading robot model 'fetch'...
[ INFO] [1689305130.276311410]: No root/virtual joint specified in SRDF. Assuming fixed joint
[FATAL] [1689305130.326138431]: Group 'arm' was not found.
```
May I ask if something missed in the [just_robot.launch](https://github.com/IRVLUTD/SceneReplica/blob/main/launch/just_robot.launch)? 
Thanks a lot!

**Comment by 07hokage** [comment]
@ZhengLeon , the error is because you need to launch moveit ros library before proceeding with any grasping.  Once you have everything installed as mentioned in the documentation section ROS Setup, You can find the launch file [moveit_sim.launch](https://github.com/IRVLUTD/SceneReplica/blob/main/launch/moveit_sim.launch) provided in the launch folder.

**Comment by ZhengLeon** [comment]
@07hokage , Thank you for your kind reply. And I will try the [moveit_sim.launch](https://github.com/IRVLUTD/SceneReplica/blob/main/launch/moveit_sim.launch).
